rancher/system-upgrade-controller

- pkg/upgrade/plan/plan.go
Sets `node.spec.unschedulable` to `false` after a job completes successfully.
This happens in the same operation that sets the **Plan**-specific tag on job success.
Fixes #9
> uncordon on upgrade job completion

- manifests/system-upgrade-controller.yaml
> manifest: deploy only on master nodes

- pkg/upgrade/job/job.go
> set HostNetwork to true on the upgrade job pod

- README.md
- examples/ubuntu/bionic.md
- examples/ubuntu/bionic.yaml
- examples/ubuntu/bionic/k3s/Dockerfile
- examples/ubuntu/bionic/k3s/agent/k3s.service
- examples/ubuntu/bionic/k3s/init.sh
- examples/ubuntu/bionic/k3s/server/k3s.service
- examples/ubuntu/docker-compose.yaml
- examples/ubuntu/k3s.yaml
- go.mod
- go.sum
- kustomization.yaml
- manifests/system-upgrade-controller.yaml
- pkg/upgrade/controller.go
- pkg/upgrade/job/job.go
- pkg/upgrade/plan/plan.go
- vendor/k8s.io/kubectl/pkg/util/hash/BUILD
- vendor/k8s.io/kubectl/pkg/util/hash/hash.go
- vendor/modules.txt
Fixes #38 by listing candidate nodes in a fixed order per plan latestHash.
Addresses the ubuntu portion of #22
Fixes #19
> ubuntu example and fix job generation

- e2e/framework/controller/deployment.go
- manifests/system-upgrade-controller.yaml
> remove toleration in controller deployment

- Dockerfile.dapper
- examples/ubuntu/docker-compose.yaml
- kustomization.yaml
- manifests/system-upgrade-controller.yaml
- scripts/package-controller
- scripts/package-e2e-tests
> prepare for v0.4.0

- pkg/upgrade/handle_core.go
- pkg/upgrade/handle_upgrade.go
> guard against nil obj in OnChange handlers

- pkg/upgrade/handle_batch.go
The job-handling logic has been re-written to be easier to follow. It should also now be more correct in that jobs from previous versions of the controller will no longer be applied and thus cause flapping for plans with cordon/drain configured.
Fixes #58
> address un-deleted legacy jobs causing flapping

- pkg/upgrade/job/job.go
> set DNSPolicy to ClusterFirstWithHostNet

- e2e/suite/plan_create_test.go
- go.mod
- go.sum
- pkg/apis/upgrade.cattle.io/v1/types.go
- pkg/generated/controllers/upgrade.cattle.io/factory.go
- pkg/generated/controllers/upgrade.cattle.io/v1/plan.go
- vendor/github.com/rancher/wrangler/pkg/apply/apply.go
- vendor/github.com/rancher/wrangler/pkg/apply/desiredset.go
- vendor/github.com/rancher/wrangler/pkg/apply/desiredset_apply.go
- vendor/github.com/rancher/wrangler/pkg/apply/desiredset_compare.go
- vendor/github.com/rancher/wrangler/pkg/apply/desiredset_owner.go
- vendor/github.com/rancher/wrangler/pkg/apply/desiredset_process.go
- vendor/github.com/rancher/wrangler/pkg/condition/condition.go
- vendor/github.com/rancher/wrangler/pkg/controller-gen/generators/factory_go.go
- vendor/github.com/rancher/wrangler/pkg/controller-gen/generators/type_go.go
- vendor/github.com/rancher/wrangler/pkg/crd/init.go
- vendor/github.com/rancher/wrangler/pkg/data/merge.go
- vendor/github.com/rancher/wrangler/pkg/generic/generating.go
- vendor/github.com/rancher/wrangler/pkg/generic/handlers.go
- vendor/github.com/rancher/wrangler/pkg/gvk/get.go
- vendor/github.com/rancher/wrangler/pkg/objectset/objectset.go
- vendor/github.com/rancher/wrangler/pkg/patch/apply.go
- vendor/github.com/rancher/wrangler/pkg/schemas/openapi/generate.go
- vendor/github.com/rancher/wrangler/pkg/schemas/reflection.go
- vendor/modules.txt
> add upgrade required tag, update wrangler version, create plan test

- README.md
- pkg/apis/upgrade.cattle.io/v1/types.go
- pkg/upgrade/job/job.go
> add SkipWaitForDeleteTimeout

- e2e/framework/channel.go
- e2e/suite/channel_resolve_test.go
- e2e/suite/plan_resolve_test.go
- pkg/upgrade/handle_upgrade.go
- pkg/upgrade/plan/plan.go
- Fix : #96 
- add validation to http response
> prevent job creation for unresolved plans

- pkg/upgrade/job/flags_test.go
- pkg/upgrade/job/job.go
testing changes in https://github.com/rancher/system-upgrade-controller/issues/88
> add unit test for skip-wait-for-delete-timeout flag

- README.md
- examples/k3s-upgrade.yaml
- pkg/apis/go.mod
- updated readme
- updated k3s-upgrade example
Addresses #103
> drain: guidance for avoiding hung upgrades

- manifests/system-upgrade-controller.yaml
https://github.com/rancher/rancher/issues/32904
> add tolerations for etcd and control-plane node taints

- kustomization.yaml
- manifests/system-upgrade-controller.yaml
Bump manifest and kustomization for 0.7.1
> manifest: v0.7.1

- kustomization.yaml
- manifests/system-upgrade-controller.yaml
> manifest: v0.7.5

- go.mod
- go.sum
> mod: wrangler v0.8.5

- pkg/upgrade/handle_batch.go
> avoid plan cache when handling jobs

- pkg/upgrade/job/job.go
> job parallelism is zero unless in applying list

- pkg/upgrade/handle_batch.go
Attempting to address #134
(cherry picked from commit 50d5e4fa6cd556b734b6bc8e45aa0241fad961eb)
> [backport release-0.7] avoid plan cache when handling jobs

- pkg/upgrade/job/job.go
Attempting to address #134
(cherry picked from commit 621bcee86072d9f35499afb1a848eb5c08bf47af)
> [backport release-0.7] job parallelism is zero unless in applying list

- .drone.yml
- rancher/dapper:v0.5.0
- plugins/release:latest
- plugins/manifest:latest
> drone: bump dapper and drone plugins

- .drone.yml
- rancher/dapper:v0.5.0
- plugins/release:latest
- plugins/manifest:latest
(cherry picked from commit 5e6e996d948667d4cf6c8e3ce22dfb406679b900)
> drone: bump dapper and drone plugins (#156)

- README.md
> fix webinar slides link

- kustomization.yaml
- manifests/system-upgrade-controller.yaml
> manifest: v0.8.0

- hack/crdgen.go
- pkg/upgrade/plan/plan.go
> add columns to plan crd

- pkg/upgrade/job/job.go
fixes https://github.com/rancher/system-upgrade-controller/issues/363
> Fix securityContext and volumes for prepare
