rancher/system-upgrade-controller

kustomization.yaml
Supports running kustomize at the repository root to generate working controller deployment manifest.
=> support kustomization of the controller manifest

main.go, pkg/apis/upgrade.cattle.io/v1/types.go, pkg/upgrade/job/job.go, pkg/upgrade/plan/plan.go, pkg/upgrade/upgrade.go, scripts/build, scripts/package, scripts/package-controller, scripts/test, scripts/version
The controller's service account is no longer utilized for upgrade jobs. This means that, unless specified on the **Plan**, upgrade jobs will get the `default` service account for the namespace.
Fixes #7 
P.S. Also lumped in here are some build script changes.
=> per-plan service account name

pkg/upgrade/job/job.go
Prevent two separate plans with the same digest/hash from generating the same job (and hence pod) names.
Fixes #32
=> fix potential clash in job/pod names

pkg/apis/upgrade.cattle.io/constants.go, pkg/upgrade/handle_batch.go, pkg/upgrade/job/job.go
This should help guarantee that completed jobs get deleted by mitigating an aggressive controller removing the `ttlSecondsAfterFinished` from the job spec.
Addresses rancher/rancher#25929
Addresses #24
=> save the ttlSecondsAfterFinished in an annotation

README.md, examples/k3s-upgrade.yaml, examples/ubuntu/bionic.md, examples/ubuntu/docker-compose.yaml, go.mod, pkg/upgrade/container/container.go, pkg/upgrade/container/container_test.go, pkg/upgrade/job/job.go
In reviewing #60 I realized that the `WithImageTag` function was buggy as well as the tests for it. So, in the spirit of the changes submitted in #60 (requested in #59) I have replaced it with `WithLatestTag` which will not override a tag if an image reference already has one. Additionally I have used this for the `prepare` container to satisfy #41.
This means that SUC interprets a tag-less image ref specified for `prepare` or `upgrade` containers to have the plan's resolved version (aka `.status.latestVersion`) instead of `latest`. Image refs with tags for `prepare` and/or `upgrade` containers are left as-is.
Fixes #41
Fixes #59
=> latest tag for prepare and upgrade containers

README.md, pkg/apis/upgrade.cattle.io/v1/types.go, pkg/apis/upgrade.cattle.io/v1/zz_generated_deepcopy.go, pkg/upgrade/job/job.go
Add `tolerations` to `plan.spec`. These will be appended to the default toleration of `node.kubernetes.io/unschedulable:NoSchedule` for pods that apply this plan.
Fixes #55
=> support plan tolerations

Dockerfile.dapper
Because that build done broke. Pinned to 3.5.4 for now.
See https://github.com/kubernetes-sigs/kustomize/issues/2462
=> build: sidestep kustomize v3.5.5

manifests/system-upgrade-controller.yaml
Added tolerations for "CriticalAddonsOnly" and "node-role.kubernetes.io/master".
The Deployment has nodeAffinity to "node-role.kubernetes.io/master", but has no tolerations.
If the master node is tainted, the Pod cannot be scheduled and stays in Pending.
=> manifests/system-upgrade-controller.yaml: Added tolerations.

pkg/upgrade/handle_batch.go, pkg/upgrade/handle_upgrade.go, pkg/upgrade/plan/plan.go
=> fix jobs exceeding plan concurrency

manifests/system-upgrade-controller.yaml
On Fedora-like distributions, /etc/ssl contains only symlinks to CA certificates. Actual certificates are stored in /etc/pki. Without mounting the later, symlinks in /etc/ssl are dangling.
Note: there's no way to detect if /etc/pki directory exists / is needed, thus usage of DirectoryOrCreate. It will cause empty /etc/pki to be created on hosts even on Debian-like distributions.
Fixes https://github.com/rancher/system-upgrade-controller/issues/105
=> manifest: mount host's /etc/pki

manifests/system-upgrade-controller.yaml
I think it shoud be `controlplane` instead of `control-plane`.
I've checked my RKE clusters and https://rancher.com/docs/rke/latest/en/config-options/nodes/ , in both cases it's `controlplane`
=> FIX: misspelled taint in manifest

pkg/upgrade/handle_upgrade.go, pkg/upgrade/job/flags_test.go, pkg/upgrade/job/job.go, pkg/upgrade/plan/plan.go
Fix job node affinity for nodes with names that do not match the value
of their `kubernetes.io/hostname` label. With this change, node names
are still reported in the **Plan**'s `.status.applying` slice but jobs are generated
with correct node-affinity via matching on the value of
`kubernetes.io/hostname`.
Fixes #119
=> adjust job node affinity to use hostname value

manifests/system-upgrade-controller.yaml
OSes like Arch Linux put certificate files in /etc/ca-certificates, and symlink to those files from /etc/ssl and /etc/pki.
This is in the same spirit as #116.
=> Mount host /etc/ca-certificates

pkg/upgrade/handle_upgrade.go, pkg/upgrade/job/job.go, pkg/upgrade/node/node.go, pkg/upgrade/plan/plan.go
Make duplicate entries for .status.applying on plans magically disappear
by correctly sorting the return value for SelectConcurrentNodes.
Fixes #132
Additionally, address a logic bug introduced in #126 that could also
spin out of control.
See
https://github.com/rancher/system-upgrade-controller/commit/90e3d082a41fefaf09d14286b880c54a28af6c21
=> fix for duplicate applying nodes

manifests/system-upgrade-controller.yaml
More recent clusters set an empty value for the node-role labels. This
change makes the SUC work out of the box with those clusters while
retaining backwards compatibility.
Fixes #136
=> Relax affinity rules for controller

pkg/upgrade/job/job.go
The Kubernetes job controller unsafely trims the Job name when setting
the GenerateName for the Job Pods, but if we keep the hostname short
we're less likely to trip over it until the bug can be fixed upstream.
Signed-off-by: Brad Davidson <brad.davidson@rancher.com>
=> Use short host name in job name

pkg/upgrade/job/job.go
The Kubernetes job controller unsafely trims the Job name when setting
the GenerateName for the Job Pods, but if we keep the hostname short
we're less likely to trip over it until the bug can be fixed upstream.
Signed-off-by: Brad Davidson <brad.davidson@rancher.com>
=> [release-0.7] Use short host name in job name

examples/k3s-upgrade.yaml, kustomization.yaml, manifests/system-upgrade-controller.yaml
Spruce up the examples with some strategic comment additions and
deletions.
=> manifest: bump suc to v0.7.6

pkg/apis/upgrade.cattle.io/constants.go, pkg/upgrade/plan/plan.go
Previously, secrets, image, and service account were used when tracking
updates of a plan with hashing. This made it impossible to trigger an
update by updating something like the environment variables.
After this change, anything in plan.Spec.Upgrade will be used in the
hash to track changes.
Issue:
https://github.com/rancher/rancher/issues/32633
https://github.com/rancher/rancher/issues/34908
=> Use plan.Spec.Upgrade in hash

pkg/upgrade/job/job.go
With the new version of wrangler, default fields are added. This poses
an issue when Apply is called again because these default fields won't
exist on the next call. This causes wrangler to think that something has
changed.
In this fix, default fields are added to the Job to prevent this issue.
Related issue:
https://github.com/rancher/rancher/issues/35819
=> Add default fields in Job

hack/crdgen.go, scripts/package-controller
=> Add CRD manifest as build artifact

.drone.yml
The github-release plugin does not exist for s390x so we need to use an alternative image.
=> Use github-release-s390x image in s390x pipeline

go.mod, go.sum
Fix for `go mod tidy` failure:
```
$ go mod tidy
go: downloading github.com/docker/distribution v2.8.0+incompatible
verifying github.com/docker/distribution@v2.8.0+incompatible: checksum mismatch
downloaded: h1:u9vuu6qqG7nN9a735Noed0ahoUm30iipVRlhgh72N0M=
go.sum:     h1:l9EaZDICImO1ngI+uTifW+ZYvvz7fKISBAKpg+MbWbY=
SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
For more information, see 'go help module-auth'.
```
=> fix for docker/distribution checksum mismatch

.drone.yml, Dockerfile.dapper, README.md, e2e/cluster/local/images/k3s/Dockerfile, e2e/cluster/local/scripts/cluster-prepare, package/Dockerfile
This PR removes the usage of alpine images and replaces them with SLE BCI images.
=> Migrate to SLE BCI images

e2e/cluster/local/images/k3s/Dockerfile, pkg/upgrade/handle_upgrade.go, scripts/e2e-sonobuoy
Ensures that owner references are properly set on the generated Job resources, so that they can be tracked by other projects that don't understand how to track relationships using the `objectset.rio.cattle.io/owner-*` annotations (which is pretty much everything).
This is a simpler version of:
* https://github.com/rancher/system-upgrade-controller/pull/220
Linked issue:
* https://github.com/rancher/system-upgrade-controller/issues/236
=> Set Kubernetes owner references on Job objects

e2e/suite/job_generate_test.go, pkg/upgrade/job/job.go, pkg/upgrade/plan/plan.go
Use helpers instead of string ops to handle pod selector generation.
The previous logic was generating invalid LabelSelector strings, and the e2e test didn't catch it because it was just looking for a substring, not the full LabelSelector value.
=> Fix Spec.Drain.PodSelector

pkg/apis/upgrade.cattle.io/v1/types.go, pkg/upgrade/job/job.go, pkg/upgrade/job/job_suite_test.go
If a workload is known to be slow in excess of the system-upgrade-controller deployment's default deadline, allow the Plan creator to specify a job deadline with the plan so that the entailing job may run to completion.
=> Allow Plan to specify Job deadline

e2e/framework/framework.go, e2e/suite/job_generate_test.go, pkg/apis/upgrade.cattle.io/v1/types.go, pkg/upgrade/handle_core.go, pkg/upgrade/plan/plan.go
add spec.secret[].ignoreUpdates to allow the definition of a secret and not trigger an update when that secret is altered
closes https://github.com/rancher/system-upgrade-controller/issues/245
duplicate of #246 but with the e2e test
=> feat: allow plan to ignore secret updates

pkg/apis/upgrade.cattle.io/constants.go, pkg/apis/upgrade.cattle.io/v1/types.go, pkg/upgrade/job/job.go
Add new field to Plan spec, Exclusive. This field will be useful when the order of execution for a series of Jobs is important, as each exclusive Job will have to complete before the next one is scheduled.
Setting the field to true will change the default behavior of how Job Pods are scheduled: it will create a PodAntiAffinity rule which will prevent more than one `exclusive` labeled SUC Job Pod from being scheduled to a node at a time, and will add this label to the Job Pod. 
If omitted or explicitly set to false, Job Pods will be scheduled according to current default behavior. 
Implements request in #225.
@dweomer
=> 225: Add support for exclusive plans

pkg/upgrade/job/job.go
Hostnames are not guaranteed safe for use in resource names; thats why the hostname has a separate field on the node object.
* For https://github.com/rancher/system-upgrade-controller/issues/273
=> Use node name for job name instead of host name

.drone.yml, pkg/upgrade/job/job.go, pkg/upgrade/job/job_suite_test.go
The `cattle.io` filtering seems a bit sketchy - is there a better way to do that?
Closes #160
=> Propagate labels and annotations from plans to jobs

e2e/suite/job_generate_test.go, pkg/apis/upgrade.cattle.io/v1/types.go, pkg/upgrade/handle_upgrade.go
It doesn't feel great to be updating the condition in the generating handler instead of the status handler, but this ensures the condition is in sync with the actual state of the plan.
I poked around a bit in the ETE test infrastructure but wasn't totally sure how to add a test for this.
Closes #291
=> Add a Complete condition to plans

kustomization.yaml, manifests/clusterrole.yaml, manifests/clusterrolebinding.yaml, manifests/system-upgrade-controller.yaml
This patch drastically cuts down the permissions of the system-upgrades-controller from the previous cluster-admin permissions to a tailored set of permissions for the controller.
=> feat: Reduce permissions for system-upgrade-controller serviceaccount

kustomization.yaml
One could also consider to hardcode the namespace in the manifest files directly, however, using kustomize reduces the overhead for future adjustments.
Fixes #294
=> fix: Add missing namespace references in rendered output

scripts/package-controller
This patch drops the deprecated flag for output reordering. This causes the output to be ordered properly instead of following the order of the resource list.
References:
https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/sortoptions/#legacy-sorting
=> fix: Drop unneeded reorder surpression

README.md, kustomization.yaml, manifests/clusterrole.yaml, manifests/system-upgrade-controller.yaml
Before this patch always version v0.8.0 would be deployed when using the
kustomize command from the README. This patch adjust the kustomization
to not overwrite the version.
The build process is unaffected from this, since during the build script
the kustomize file is adjusted to adjust the version to the current
release. This means the build manifests for release will still have a
pinned version like before.
Reference:
https://github.com/rancher/system-upgrade-controller/blob/4eacc2dabbde943ee59dc7819ea0a04909b05b0f/scripts/package-controller#L36
=> Update/fix README kustomize command

manifests/clusterrole.yaml
fix: system-upgrade-controller-drainer: add missing delete permission for pods in clusterrole
Fixes #319
=> fix: system-upgrade-controller-drainer: add missing delete permission for pods in clusterrole

.github/workflows/release.yaml
* Fixes issue where releases would be left without assets if the tag was created by the GH release UI, as the release would already exist.
* Fixes issue where arm64 image is overwriting the amd64 image
=> Fix GHA release workflow

.github/workflows/release.yaml
Passing the binary artifacts through the GH artifact zip files strips their permissions; we need to make them executable before building the final image.
=> Fix artifact permissions

kustomization.yaml, manifests/system-upgrade-controller.yaml
This reverts commit [4e31e5d6a0926df9f370a06c9ea3250ee1e088b1](https://github.com/rancher/system-upgrade-controller/commit/4e31e5d6a0926df9f370a06c9ea3250ee1e088b1).
This "fixes" issue #302 by reverting the commit that caused the issue.
Currently some installations break because of the missing `latest` tag on the [docker hub](https://hub.docker.com/r/rancher/system-upgrade-controller/tags) as explained by @brandond [here](https://github.com/rancher/system-upgrade-controller/commit/4e31e5d6a0926df9f370a06c9ea3250ee1e088b1#r139564543)
I suggest reverting this PR once a 'latest' tag has been added to the docker hub but for now keep installations working by using a version tag instead of a latest tag.
=> Revert "fix(kustomize): Deploy latest system-upgrade-controller"

package/Dockerfile, pkg/upgrade/plan/plan.go
Add timezone files to Docker image so that tz names work in spec.window.timeZone. 
These worked in test because tests run in a BCI image, but the shipping docker image is `FROM scratch` and was missing the files. 
We have to use Alpine as the source for zoneinfo, as BCI does not provide 32bit arm images.
Issue:
* https://github.com/rancher/system-upgrade-controller/issues/342
=> Include tz files in Docker image

package/Dockerfile
This allows renovate to find the source repo to fetch changelogs. 🤗
=> feat: add `org.opencontainers.image.source` docker label

pkg/upgrade/handle_upgrade.go, pkg/upgrade/job/job.go, pkg/upgrade/plan/plan.go
Fixes issue where nonexistent secret with ignoreUpdate set would cause the plan to endlessly requeue due to errors. If it is ignored for purposes of plan hash, it should be optional.
* https://github.com/rancher/system-upgrade-controller/issues/346
=> Make IgnoreUpdate secrets optional
